### ISSUE TITLE
dresa/photo-quality in end-user software ?

### ISSUE THREAD

**Issue by haukebasse** [dresa/photo-quality#2]
Hi Dresa

I read the documentation of your project and I am quite impressed; thorough work ! I very much like the scientific thoroughness that you have applied in your proceeding.
I had been searching for a simple tool to evaluate image sharpness, at best directly in irfan view or so.
But it seems the apparently simple functionality of calculating a measure for sharpness is not at all implemented in standard, end-user software.
Then I found your project, which goes way beyond what I had looked for.
Do you know whether your code or has been implemented into any end user software, such as IrfanView or XnView ? 
Or if not, by chance, whether any end-user software can "simply" calculate  sharpness?

My ultimate goal would be to realize something as follows:
When photos do not have a high sharpness, it seems to me that one could save them in a rather high jpg compression level without significant quality-losses.
I had the idea that it should be not too hard to figure out the sweet spot level of compression, until which the quality loss is neglegible respectively from which on the losses become siginificant compared to the savings in file size.
Afterwards the compressed image would be saved, with smaller file size but still almost same quality.

Kind regards, Hauke 

PS.: Actually, perhaps sharpness is not even the right measure for expressing the loss of quality when jpg-ing photos? I assume you know without much thinking which measure is best for expressing the quality loss when saving as jpg with high compression rates. I'd be grateful if you could give me a hint. (09.10.20)

**Comment by dresa** [comment]
Hi Hauke,

Nice to hear you found the methodology interesting!
As far as I know, my code is not part of any readily available software. As you said, many image measurements, such as sharpness, seem like simple things to do, but there exists a large variety of methods whose details are somewhat obscure. I guess the lack of standardization comes from the fact that sharpness is actually a complex concept, involving not only idealized RGB color spaces, but also optics, the physiology of human eye, perception, and even culture! No matter what the definition is, I'm happy to use any methods available to measure image quality in photographic sense.

I like your idea on using sharpness for _dynamic_ image compression! I believe a suitable method for sharpness you are looking for depends on the model you use to compress image data. Who knows, perhaps using a simple unsharp mask method and measuring a difference (say, in CIELUV space) between original and noised image gives a good estimate on how much compression is ideal. In case your compression method is iterative, criteria such as BIC, AIC, or MDL could be used to find the sweet spot for compression. If I remember correctly, JPEG 2000 (or was it something else) uses variable block size depending on loss in quality.

Now that I think of it, many other criteria can be used to compress an image as well. For choosing an ideal number of colored segments (as seen in the README), I use in my code a Minimum Description Length (MDL), which is closely related to image compression; in fact MDL produces a representation for the image that can be encoded with fewest number of bits (encoded model parameters + encoded model data + encoded differences with model and original) w.r.t chosen model family. Adjusting the difference measure to better match perceived _loss in quality_ (rather than a technical difference measure that I use) is something to consider.

The question about a _loss in quality_ is indeed interesting. While simple solutions exist, the variation in the viewers' opinions is so wide that no method covers all needs -- there is always room for specialized ideas just like yours. Good luck!

Kind regards,
Esa

**Comment by haukebasse** [comment]
Hi Dresa,

 

thx for your thorough answer !

 

I see that my fear, that measuring sharpness or – broader – quality loss by jpg-ing can be complex, is true.

 

I personally do not have the knowledge for implementing something like this, and also not the time to work myself into this wide domain.

Further studies as well as realization might be interesting subjects for master theses. Do you happen to know any college or university chairs to which I might direct this as a proposal ?

 

Kind regards, Hauke 

 

 
 

Gesendet: Freitag, 09. Oktober 2020 um 15:09 Uhr
Von: "Esa Junttila" <notifications@github.com>
An: "dresa/photo-quality" <photo-quality@noreply.github.com>
Cc: "haukebasse" <hauke.basse@gmx.net>, "Author" <author@noreply.github.com>
Betreff: Re: [dresa/photo-quality] dresa/photo-quality in end-user software ? (#2)


 

Hi Hauke,

Nice to hear you found the methodology interesting!
As far as I know, my code is not part of any readily available software. As you said, many image measurements, such as sharpness, seem like simple things to do, but there exists a large variety of methods whose details are somewhat obscure. I guess the lack of standardization comes from the fact that sharpness is actually a complex concept, involving not only idealized RGB color spaces, but also optics, the physiology of human eye, perception, and even culture! No matter what the definition is, I'm happy to use any methods available to measure image quality in photographic sense.

I like your idea on using sharpness for dynamic image compression! I believe a suitable method for sharpness you are looking for depends on the model you use to compress image data. Who knows, perhaps using a simple unsharp mask method and measuring a difference (say, in CIELUV space) between original and noised image gives a good estimate on how much compression is ideal. In case your compression method is iterative, criteria such as BIC, AIC, or MDL could be used to find the sweet spot for compression. If I remember correctly, JPEG 2000 (or was it something else) uses variable block size depending on loss in quality.

Now that I think of it, many other criteria can be used to compress an image as well. For choosing an ideal number of colored segments (as seen in the README), I use in my code a Minimum Description Length (MDL), which is closely related to image compression; in fact MDL produces a representation for the image that can be encoded with fewest number of bits (encoded model parameters + encoded model data + encoded differences with model and original) w.r.t chosen model family. Adjusting the difference measure to better match perceived loss in quality (rather than a technical difference measure that I use) is something to consider.

The question about a loss in quality is indeed interesting. While simple solutions exist, the variation in the viewers' opinions is so wide that no method covers all needs -- there is always room for specialized ideas just like yours. Good luck!

Kind regards,
Esa

**Comment by dresa** [comment]
Many mathematical and computer science MSc theses involve different image-processing methodologies. I have read a few theses on photo focus-stacking in the past. Anyway, I think the topic you are proposing has quite a wide appeal, so with a bit of luck you'll find a university and professors that are happy to pursue further with this theme. I hope it turns out well!

**Comment by haukebasse** [comment]
Thanks again; I will look for researchers on this field in the internet and then propose my idea to them. I'll also mention that part of your work might be helpful therefor.
If anybody else is reading this and has further hints, please drop them here !  :) 
Kind regards, Hauke
